parameters:
  - name: orc8rDbPassword
    type: string
    displayName: Orchestrator DB Password
  - name: orc8rDbHost
    type: string
    displayName: Orchestrator DB Host

steps:
#- script: mkdir -p $(Agent.BuildDirectory)\s\magma
#- script: mkdir -p $(Agent.BuildDirectory)\s\magma-overrides
- checkout: self
  path: s
- checkout: Overrides
  path: overrides
- script: |
    mkdir -p ~/secrets
    cp -r $(Agent.BuildDirectory)/overrides/certs/ ~/secrets/certs/
    ls ~/secrets/certs

    mkdir -p ~/secrets/envdir
    echo "STREAMER,SUBSCRIBERDB,METRICSD,CERTIFIER,BOOTSTRAPPER,METERINGD_RECORDS,ACCESSD,OBSIDIAN,DISPATCHER,DIRECTORYD" > ~/secrets/envdir/CONTROLLER_SERVICES
    echo "dbname=orc8r user=orc8r password=${{ parameters.orc8rDbPassword}} host=${{ parameters.orc8rDbHost }}" > ~/secrets/envdir/DATABASE_SOURCE
    
    cat ~/secrets/envdir/DATABASE_SOURCE
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: '3.1.0'
# - task: HelmDeploy@0
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscription: 'Alex - Subscription'
#     azureResourceGroup: 'sonar'
#     kubernetesCluster: 'alexsonar'
#     namespace: 'magma-stage'
#     command: 'upgrade'
#     chartType: 'FilePath'
#     chartPath: 'orc8r/cloud/helm/orc8r'
#     releaseName: 'orc8r'
#     valueFile: 'orc8r/cloud/helm/orc8r/vals.yml'
- task: Kubernetes@1
  displayName: 'Create a new namespace for the pull request'
  inputs:
    command: apply
    useConfigurationFile: true
    inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(k8sNamespaceForPR)" }}'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Alex - Subscription'
    azureResourceGroup: 'sonar'
    kubernetesCluster: 'alexsonar'
    command: 'create'
    arguments: 'namespace magma-prod'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'