resources:
  repositories:
  - repository: Overrides
    type: github
    endpoint: bluechipalex - pat
    name: bluechipalex/magma-overrides

trigger:
- master

stages:
- stage: Configure
  jobs:
    - job: Configure
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - checkout: self
      - checkout: Overrides
      - task: Bash@3
        displayName: Script
        inputs:
          targetType: 'inline'
          script: echo "Hello!"
      - script: dir $(Build.SourcesDirectory)
      - task: HelmInstaller@1
        inputs:
          helmVersionToInstall: '3.1.0'
      # - task: HelmDeploy@0
      #   inputs:
      #     connectionType: 'Azure Resource Manager'
      #     azureSubscription: 'Alex - Subscription'
      #     azureResourceGroup: 'sonar'
      #     kubernetesCluster: 'alexsonar'
      #     namespace: 'magma-stage'
      #     command: 'upgrade'
      #     chartType: 'FilePath'
      #     chartPath: 'orc8r/cloud/helm/orc8r'
      #     releaseName: 'orc8r'
      #     valueFile: 'orc8r/cloud/helm/orc8r/vals.yml'
