trigger:
- master

resources:
  repositories:
  - repository: Overrides
    type: github
    endpoint: bluechipalex - pat
    name: bluechipalex/magma-overrides

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: aks-pipeline.yml
    parameters:
      orc8rDbPassword: BlueChip!!
      orc8rDbHost: testing.com
